apiVersion: v1
kind: Service
metadata:
  name: rollout-canary-active
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: golang-sample-app
